### ISSUE TITLE
The new version can not run.  

### ISSUE THREAD

**Issue by CHCP** [tookit/vue-material-admin#28]
I install new version, install some plugins manually such as less, but it can not run:
```
> vue-material-admin@1.0.0 dev D:\work\vue-material-admin-master
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% after seal

 ERROR  Failed to compile with 1 errors                                                                  06:36:22
 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\work\vue-material-admin-master\node_modules\babel-preset-stage-2\lib\index.js
    at createDescriptor (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (native)
    at createDescriptors (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-chain.js:315:26)
    at D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-chain.js:278:7
    at buildRootChain (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\config-chain.js:118:22)
    at loadPrivatePartialConfig (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\partial.js:57:55)
    at Object.loadPartialConfig (D:\work\vue-material-admin-master\node_modules\@babel\core\lib\config\partial.js:82:18)
    at Object.<anonymous> (D:\work\vue-material-admin-master\node_modules\babel-loader\lib\index.js:140:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\work\vue-material-admin-master\node_modules\babel-loader\lib\index.js:3:103)
    at _next (D:\work\vue-material-admin-master\node_modules\babel-loader\lib\index.js:5:194)
    at D:\work\vue-material-admin-master\node_modules\babel-loader\lib\index.js:5:364
 @ multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/main.js
 ```

**Comment by ureshpatel** [comment]
https://github.com/tookit/vue-material-admin/issues/29

**Comment by tookit** [comment]
`npm run dev` or `npm run build`

**Comment by ureshpatel** [comment]
Hello Michael,
How are you ?
Can you please looking to my post as well. 
We made this admin with all functionality but now when uplaod to aws server and "npm run build" then it happen crash.

https://github.com/tookit/vue-material-admin/issues/29

Thank You,
Uresh

**Comment by tookit** [comment]
fixed. pls try again

**Comment by CHCP** [comment]
OK, Thanks.
