### ISSUE TITLE
ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.

### ISSUE THREAD

**Issue by lixing0323** [tookit/vue-material-admin#72]
npm run serve

> vma@0.1.0 serve /Users/lixing/Learning/vue/vue-material-admin
> vue-cli-service serve

 INFO  Starting development server...
 ERROR  Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
Error: [VuetifyLoaderPlugin Error] No matching rule for vue-loader found.
Make sure there is at least one root-level rule that uses vue-loader.
    at VuetifyLoaderPlugin.apply (/Users/lixing/Learning/vue/vue-material-admin/node_modules/vuetify-loader/lib/plugin.js:18:13)
    at webpack (/Users/lixing/Learning/vue/vue-material-admin/node_modules/webpack/lib/webpack.js:51:13)
    at serve (/Users/lixing/Learning/vue/vue-material-admin/node_modules/@vue/cli-service/lib/commands/serve.js:163:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vma@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vma@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by tookit** [comment]
what's your env? yarn version?

**Comment by linqhkobe** [comment]
you can try  ‘yarn install’ ,  I met
If it happens ‘The engine "node" is incompatible with this module ’
you can enter ‘ yarn config set ignore-engines true’
